# Server
server.port=8082

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/sparesy?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
logging.level.org.hibernate=ERROR
logging.level.org.springframework=ERROR
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# JWT — must match auth-service exactly
jwt.secret=sparesy-super-secret-key-for-jwt-signing-2026
jwt.expiration=86400000

#To tell Spring to use JWT filter.
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# File uploads
file.upload.dir=./uploads

springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/api-docs